// Generated by tools/generate_foundation.py. Edit that table, then regenerate.
import 'color.dart';
import 'contract.dart';
import 'theme.dart';

/// Aurora foundation v1: current Material color roles plus status roles.
abstract final class AuroraFoundation {
  static const version = 1;
  static const primary = AuroraColorToken('colors.primary',
      description: 'Accent for prominent actions.');
  static const onPrimary = AuroraColorToken('colors.onPrimary',
      description: 'Text and icons on primary.');
  static const primaryContainer = AuroraColorToken('colors.primaryContainer',
      description: 'Lower-emphasis container for prominent actions.');
  static const onPrimaryContainer = AuroraColorToken(
      'colors.onPrimaryContainer',
      description: 'Text and icons on primaryContainer.');
  static const primaryFixed = AuroraColorToken('colors.primaryFixed',
      description: 'Container accent that stays constant across appearances.');
  static const primaryFixedDim = AuroraColorToken('colors.primaryFixedDim',
      description: 'Stronger fixed primary accent.');
  static const onPrimaryFixed = AuroraColorToken('colors.onPrimaryFixed',
      description: 'Text and icons on fixed primary accents.');
  static const onPrimaryFixedVariant = AuroraColorToken(
      'colors.onPrimaryFixedVariant',
      description: 'Lower-emphasis content on fixed primary accents.');
  static const secondary = AuroraColorToken('colors.secondary',
      description: 'Accent for less prominent actions.');
  static const onSecondary = AuroraColorToken('colors.onSecondary',
      description: 'Text and icons on secondary.');
  static const secondaryContainer = AuroraColorToken(
      'colors.secondaryContainer',
      description: 'Lower-emphasis container for less prominent actions.');
  static const onSecondaryContainer = AuroraColorToken(
      'colors.onSecondaryContainer',
      description: 'Text and icons on secondaryContainer.');
  static const secondaryFixed = AuroraColorToken('colors.secondaryFixed',
      description: 'Container accent that stays constant across appearances.');
  static const secondaryFixedDim = AuroraColorToken('colors.secondaryFixedDim',
      description: 'Stronger fixed secondary accent.');
  static const onSecondaryFixed = AuroraColorToken('colors.onSecondaryFixed',
      description: 'Text and icons on fixed secondary accents.');
  static const onSecondaryFixedVariant = AuroraColorToken(
      'colors.onSecondaryFixedVariant',
      description: 'Lower-emphasis content on fixed secondary accents.');
  static const tertiary = AuroraColorToken('colors.tertiary',
      description: 'Accent for contrasting accents.');
  static const onTertiary = AuroraColorToken('colors.onTertiary',
      description: 'Text and icons on tertiary.');
  static const tertiaryContainer = AuroraColorToken('colors.tertiaryContainer',
      description: 'Lower-emphasis container for contrasting accents.');
  static const onTertiaryContainer = AuroraColorToken(
      'colors.onTertiaryContainer',
      description: 'Text and icons on tertiaryContainer.');
  static const tertiaryFixed = AuroraColorToken('colors.tertiaryFixed',
      description: 'Container accent that stays constant across appearances.');
  static const tertiaryFixedDim = AuroraColorToken('colors.tertiaryFixedDim',
      description: 'Stronger fixed tertiary accent.');
  static const onTertiaryFixed = AuroraColorToken('colors.onTertiaryFixed',
      description: 'Text and icons on fixed tertiary accents.');
  static const onTertiaryFixedVariant = AuroraColorToken(
      'colors.onTertiaryFixedVariant',
      description: 'Lower-emphasis content on fixed tertiary accents.');
  static const error = AuroraColorToken('colors.error',
      description: 'Error and destructive feedback.');
  static const onError = AuroraColorToken('colors.onError',
      description: 'Text and icons on error.');
  static const errorContainer = AuroraColorToken('colors.errorContainer',
      description: 'Lower-emphasis error container.');
  static const onErrorContainer = AuroraColorToken('colors.onErrorContainer',
      description: 'Text and icons on errorContainer.');
  static const surface = AuroraColorToken('colors.surface',
      description: 'Default page and component surface.');
  static const onSurface = AuroraColorToken('colors.onSurface',
      description: 'Primary text and icons on surfaces.');
  static const surfaceDim = AuroraColorToken('colors.surfaceDim',
      description: 'Dimmest surface tone.');
  static const surfaceBright = AuroraColorToken('colors.surfaceBright',
      description: 'Brightest surface tone.');
  static const surfaceContainerLowest = AuroraColorToken(
      'colors.surfaceContainerLowest',
      description: 'Lowest surface container level.');
  static const surfaceContainerLow = AuroraColorToken(
      'colors.surfaceContainerLow',
      description: 'Low surface container level.');
  static const surfaceContainer = AuroraColorToken('colors.surfaceContainer',
      description: 'Default distinct surface container.');
  static const surfaceContainerHigh = AuroraColorToken(
      'colors.surfaceContainerHigh',
      description: 'High surface container level.');
  static const surfaceContainerHighest = AuroraColorToken(
      'colors.surfaceContainerHighest',
      description: 'Highest surface container level.');
  static const onSurfaceVariant = AuroraColorToken('colors.onSurfaceVariant',
      description: 'Lower-emphasis text and icons on surfaces.');
  static const outline = AuroraColorToken('colors.outline',
      description: 'Boundaries requiring emphasis.');
  static const outlineVariant = AuroraColorToken('colors.outlineVariant',
      description: 'Subtle decorative boundaries and dividers.');
  static const shadow =
      AuroraColorToken('colors.shadow', description: 'Color of cast shadows.');
  static const scrim = AuroraColorToken('colors.scrim',
      description: 'Color of obscuring modal overlays.');
  static const inverseSurface = AuroraColorToken('colors.inverseSurface',
      description: 'Surface contrasting with surrounding appearance.');
  static const onInverseSurface = AuroraColorToken('colors.onInverseSurface',
      description: 'Text and icons on inverseSurface.');
  static const inversePrimary = AuroraColorToken('colors.inversePrimary',
      description: 'Primary accent on inverseSurface.');
  static const surfaceTint = AuroraColorToken('colors.surfaceTint',
      description: 'Accent used by Material surface tint treatments.');
  static const success =
      AuroraColorToken('colors.success', description: 'Success feedback.');
  static const onSuccess = AuroraColorToken('colors.onSuccess',
      description: 'Text and icons on success.');
  static const successContainer = AuroraColorToken('colors.successContainer',
      description: 'Lower-emphasis success container.');
  static const onSuccessContainer = AuroraColorToken(
      'colors.onSuccessContainer',
      description: 'Text and icons on successContainer.');
  static const warning =
      AuroraColorToken('colors.warning', description: 'Warning feedback.');
  static const onWarning = AuroraColorToken('colors.onWarning',
      description: 'Text and icons on warning.');
  static const warningContainer = AuroraColorToken('colors.warningContainer',
      description: 'Lower-emphasis warning container.');
  static const onWarningContainer = AuroraColorToken(
      'colors.onWarningContainer',
      description: 'Text and icons on warningContainer.');
  static const info =
      AuroraColorToken('colors.info', description: 'Info feedback.');
  static const onInfo =
      AuroraColorToken('colors.onInfo', description: 'Text and icons on info.');
  static const infoContainer = AuroraColorToken('colors.infoContainer',
      description: 'Lower-emphasis info container.');
  static const onInfoContainer = AuroraColorToken('colors.onInfoContainer',
      description: 'Text and icons on infoContainer.');
  static const tokens = <AuroraColorToken>[
    primary,
    onPrimary,
    primaryContainer,
    onPrimaryContainer,
    primaryFixed,
    primaryFixedDim,
    onPrimaryFixed,
    onPrimaryFixedVariant,
    secondary,
    onSecondary,
    secondaryContainer,
    onSecondaryContainer,
    secondaryFixed,
    secondaryFixedDim,
    onSecondaryFixed,
    onSecondaryFixedVariant,
    tertiary,
    onTertiary,
    tertiaryContainer,
    onTertiaryContainer,
    tertiaryFixed,
    tertiaryFixedDim,
    onTertiaryFixed,
    onTertiaryFixedVariant,
    error,
    onError,
    errorContainer,
    onErrorContainer,
    surface,
    onSurface,
    surfaceDim,
    surfaceBright,
    surfaceContainerLowest,
    surfaceContainerLow,
    surfaceContainer,
    surfaceContainerHigh,
    surfaceContainerHighest,
    onSurfaceVariant,
    outline,
    outlineVariant,
    shadow,
    scrim,
    inverseSurface,
    onInverseSurface,
    inversePrimary,
    surfaceTint,
    success,
    onSuccess,
    successContainer,
    onSuccessContainer,
    warning,
    onWarning,
    warningContainer,
    onWarningContainer,
    info,
    onInfo,
    infoContainer,
    onInfoContainer,
  ];
}

/// Direct immutable values for the entire app contract. No global active theme.
final class AuroraTokens {
  const AuroraTokens(this._variant);
  final AuroraThemeVariant _variant;
  AuroraColor read(AuroraColorToken token) => _variant.read(token);
  AuroraColor get primary => _variant.read(AuroraFoundation.primary);
  AuroraColor get onPrimary => _variant.read(AuroraFoundation.onPrimary);
  AuroraColor get primaryContainer =>
      _variant.read(AuroraFoundation.primaryContainer);
  AuroraColor get onPrimaryContainer =>
      _variant.read(AuroraFoundation.onPrimaryContainer);
  AuroraColor get primaryFixed => _variant.read(AuroraFoundation.primaryFixed);
  AuroraColor get primaryFixedDim =>
      _variant.read(AuroraFoundation.primaryFixedDim);
  AuroraColor get onPrimaryFixed =>
      _variant.read(AuroraFoundation.onPrimaryFixed);
  AuroraColor get onPrimaryFixedVariant =>
      _variant.read(AuroraFoundation.onPrimaryFixedVariant);
  AuroraColor get secondary => _variant.read(AuroraFoundation.secondary);
  AuroraColor get onSecondary => _variant.read(AuroraFoundation.onSecondary);
  AuroraColor get secondaryContainer =>
      _variant.read(AuroraFoundation.secondaryContainer);
  AuroraColor get onSecondaryContainer =>
      _variant.read(AuroraFoundation.onSecondaryContainer);
  AuroraColor get secondaryFixed =>
      _variant.read(AuroraFoundation.secondaryFixed);
  AuroraColor get secondaryFixedDim =>
      _variant.read(AuroraFoundation.secondaryFixedDim);
  AuroraColor get onSecondaryFixed =>
      _variant.read(AuroraFoundation.onSecondaryFixed);
  AuroraColor get onSecondaryFixedVariant =>
      _variant.read(AuroraFoundation.onSecondaryFixedVariant);
  AuroraColor get tertiary => _variant.read(AuroraFoundation.tertiary);
  AuroraColor get onTertiary => _variant.read(AuroraFoundation.onTertiary);
  AuroraColor get tertiaryContainer =>
      _variant.read(AuroraFoundation.tertiaryContainer);
  AuroraColor get onTertiaryContainer =>
      _variant.read(AuroraFoundation.onTertiaryContainer);
  AuroraColor get tertiaryFixed =>
      _variant.read(AuroraFoundation.tertiaryFixed);
  AuroraColor get tertiaryFixedDim =>
      _variant.read(AuroraFoundation.tertiaryFixedDim);
  AuroraColor get onTertiaryFixed =>
      _variant.read(AuroraFoundation.onTertiaryFixed);
  AuroraColor get onTertiaryFixedVariant =>
      _variant.read(AuroraFoundation.onTertiaryFixedVariant);
  AuroraColor get error => _variant.read(AuroraFoundation.error);
  AuroraColor get onError => _variant.read(AuroraFoundation.onError);
  AuroraColor get errorContainer =>
      _variant.read(AuroraFoundation.errorContainer);
  AuroraColor get onErrorContainer =>
      _variant.read(AuroraFoundation.onErrorContainer);
  AuroraColor get surface => _variant.read(AuroraFoundation.surface);
  AuroraColor get onSurface => _variant.read(AuroraFoundation.onSurface);
  AuroraColor get surfaceDim => _variant.read(AuroraFoundation.surfaceDim);
  AuroraColor get surfaceBright =>
      _variant.read(AuroraFoundation.surfaceBright);
  AuroraColor get surfaceContainerLowest =>
      _variant.read(AuroraFoundation.surfaceContainerLowest);
  AuroraColor get surfaceContainerLow =>
      _variant.read(AuroraFoundation.surfaceContainerLow);
  AuroraColor get surfaceContainer =>
      _variant.read(AuroraFoundation.surfaceContainer);
  AuroraColor get surfaceContainerHigh =>
      _variant.read(AuroraFoundation.surfaceContainerHigh);
  AuroraColor get surfaceContainerHighest =>
      _variant.read(AuroraFoundation.surfaceContainerHighest);
  AuroraColor get onSurfaceVariant =>
      _variant.read(AuroraFoundation.onSurfaceVariant);
  AuroraColor get outline => _variant.read(AuroraFoundation.outline);
  AuroraColor get outlineVariant =>
      _variant.read(AuroraFoundation.outlineVariant);
  AuroraColor get shadow => _variant.read(AuroraFoundation.shadow);
  AuroraColor get scrim => _variant.read(AuroraFoundation.scrim);
  AuroraColor get inverseSurface =>
      _variant.read(AuroraFoundation.inverseSurface);
  AuroraColor get onInverseSurface =>
      _variant.read(AuroraFoundation.onInverseSurface);
  AuroraColor get inversePrimary =>
      _variant.read(AuroraFoundation.inversePrimary);
  AuroraColor get surfaceTint => _variant.read(AuroraFoundation.surfaceTint);
  AuroraColor get success => _variant.read(AuroraFoundation.success);
  AuroraColor get onSuccess => _variant.read(AuroraFoundation.onSuccess);
  AuroraColor get successContainer =>
      _variant.read(AuroraFoundation.successContainer);
  AuroraColor get onSuccessContainer =>
      _variant.read(AuroraFoundation.onSuccessContainer);
  AuroraColor get warning => _variant.read(AuroraFoundation.warning);
  AuroraColor get onWarning => _variant.read(AuroraFoundation.onWarning);
  AuroraColor get warningContainer =>
      _variant.read(AuroraFoundation.warningContainer);
  AuroraColor get onWarningContainer =>
      _variant.read(AuroraFoundation.onWarningContainer);
  AuroraColor get info => _variant.read(AuroraFoundation.info);
  AuroraColor get onInfo => _variant.read(AuroraFoundation.onInfo);
  AuroraColor get infoContainer =>
      _variant.read(AuroraFoundation.infoContainer);
  AuroraColor get onInfoContainer =>
      _variant.read(AuroraFoundation.onInfoContainer);
}
