// Generated by tools/generate_foundation.py. Edit that table, then regenerate.
import 'package:material_color_utilities/material_color_utilities.dart';
import 'color.dart';
import 'contract.dart';
import 'foundation.dart';

Map<AuroraColorToken, AuroraColor> materialRoleValues(DynamicScheme scheme) => {
      AuroraFoundation.primary: AuroraColor(scheme.primary),
      AuroraFoundation.onPrimary: AuroraColor(scheme.onPrimary),
      AuroraFoundation.primaryContainer: AuroraColor(scheme.primaryContainer),
      AuroraFoundation.onPrimaryContainer:
          AuroraColor(scheme.onPrimaryContainer),
      AuroraFoundation.primaryFixed: AuroraColor(scheme.primaryFixed),
      AuroraFoundation.primaryFixedDim: AuroraColor(scheme.primaryFixedDim),
      AuroraFoundation.onPrimaryFixed: AuroraColor(scheme.onPrimaryFixed),
      AuroraFoundation.onPrimaryFixedVariant:
          AuroraColor(scheme.onPrimaryFixedVariant),
      AuroraFoundation.secondary: AuroraColor(scheme.secondary),
      AuroraFoundation.onSecondary: AuroraColor(scheme.onSecondary),
      AuroraFoundation.secondaryContainer:
          AuroraColor(scheme.secondaryContainer),
      AuroraFoundation.onSecondaryContainer:
          AuroraColor(scheme.onSecondaryContainer),
      AuroraFoundation.secondaryFixed: AuroraColor(scheme.secondaryFixed),
      AuroraFoundation.secondaryFixedDim: AuroraColor(scheme.secondaryFixedDim),
      AuroraFoundation.onSecondaryFixed: AuroraColor(scheme.onSecondaryFixed),
      AuroraFoundation.onSecondaryFixedVariant:
          AuroraColor(scheme.onSecondaryFixedVariant),
      AuroraFoundation.tertiary: AuroraColor(scheme.tertiary),
      AuroraFoundation.onTertiary: AuroraColor(scheme.onTertiary),
      AuroraFoundation.tertiaryContainer: AuroraColor(scheme.tertiaryContainer),
      AuroraFoundation.onTertiaryContainer:
          AuroraColor(scheme.onTertiaryContainer),
      AuroraFoundation.tertiaryFixed: AuroraColor(scheme.tertiaryFixed),
      AuroraFoundation.tertiaryFixedDim: AuroraColor(scheme.tertiaryFixedDim),
      AuroraFoundation.onTertiaryFixed: AuroraColor(scheme.onTertiaryFixed),
      AuroraFoundation.onTertiaryFixedVariant:
          AuroraColor(scheme.onTertiaryFixedVariant),
      AuroraFoundation.error: AuroraColor(scheme.error),
      AuroraFoundation.onError: AuroraColor(scheme.onError),
      AuroraFoundation.errorContainer: AuroraColor(scheme.errorContainer),
      AuroraFoundation.onErrorContainer: AuroraColor(scheme.onErrorContainer),
      AuroraFoundation.surface: AuroraColor(scheme.surface),
      AuroraFoundation.onSurface: AuroraColor(scheme.onSurface),
      AuroraFoundation.surfaceDim: AuroraColor(scheme.surfaceDim),
      AuroraFoundation.surfaceBright: AuroraColor(scheme.surfaceBright),
      AuroraFoundation.surfaceContainerLowest:
          AuroraColor(scheme.surfaceContainerLowest),
      AuroraFoundation.surfaceContainerLow:
          AuroraColor(scheme.surfaceContainerLow),
      AuroraFoundation.surfaceContainer: AuroraColor(scheme.surfaceContainer),
      AuroraFoundation.surfaceContainerHigh:
          AuroraColor(scheme.surfaceContainerHigh),
      AuroraFoundation.surfaceContainerHighest:
          AuroraColor(scheme.surfaceContainerHighest),
      AuroraFoundation.onSurfaceVariant: AuroraColor(scheme.onSurfaceVariant),
      AuroraFoundation.outline: AuroraColor(scheme.outline),
      AuroraFoundation.outlineVariant: AuroraColor(scheme.outlineVariant),
      AuroraFoundation.shadow: AuroraColor(scheme.shadow),
      AuroraFoundation.scrim: AuroraColor(scheme.scrim),
      AuroraFoundation.inverseSurface: AuroraColor(scheme.inverseSurface),
      AuroraFoundation.onInverseSurface: AuroraColor(scheme.inverseOnSurface),
      AuroraFoundation.inversePrimary: AuroraColor(scheme.inversePrimary),
      AuroraFoundation.surfaceTint: AuroraColor(scheme.surfaceTint),
    };
