// Generated by tools/generate_foundation.py. Edit that table, then regenerate.
import 'package:aurora/aurora.dart';
import 'package:flutter/material.dart';

extension AuroraFlutterColor on AuroraColor {
  Color get flutterColor => Color(argb);
}

/// Supplies every nondeprecated Material color role explicitly.
extension AuroraMaterialVariant on AuroraThemeVariant {
  ColorScheme toColorScheme() => ColorScheme(
        brightness: appearance == AuroraAppearance.light
            ? Brightness.light
            : Brightness.dark,
        primary: colors.primary.flutterColor,
        onPrimary: colors.onPrimary.flutterColor,
        primaryContainer: colors.primaryContainer.flutterColor,
        onPrimaryContainer: colors.onPrimaryContainer.flutterColor,
        primaryFixed: colors.primaryFixed.flutterColor,
        primaryFixedDim: colors.primaryFixedDim.flutterColor,
        onPrimaryFixed: colors.onPrimaryFixed.flutterColor,
        onPrimaryFixedVariant: colors.onPrimaryFixedVariant.flutterColor,
        secondary: colors.secondary.flutterColor,
        onSecondary: colors.onSecondary.flutterColor,
        secondaryContainer: colors.secondaryContainer.flutterColor,
        onSecondaryContainer: colors.onSecondaryContainer.flutterColor,
        secondaryFixed: colors.secondaryFixed.flutterColor,
        secondaryFixedDim: colors.secondaryFixedDim.flutterColor,
        onSecondaryFixed: colors.onSecondaryFixed.flutterColor,
        onSecondaryFixedVariant: colors.onSecondaryFixedVariant.flutterColor,
        tertiary: colors.tertiary.flutterColor,
        onTertiary: colors.onTertiary.flutterColor,
        tertiaryContainer: colors.tertiaryContainer.flutterColor,
        onTertiaryContainer: colors.onTertiaryContainer.flutterColor,
        tertiaryFixed: colors.tertiaryFixed.flutterColor,
        tertiaryFixedDim: colors.tertiaryFixedDim.flutterColor,
        onTertiaryFixed: colors.onTertiaryFixed.flutterColor,
        onTertiaryFixedVariant: colors.onTertiaryFixedVariant.flutterColor,
        error: colors.error.flutterColor,
        onError: colors.onError.flutterColor,
        errorContainer: colors.errorContainer.flutterColor,
        onErrorContainer: colors.onErrorContainer.flutterColor,
        surface: colors.surface.flutterColor,
        onSurface: colors.onSurface.flutterColor,
        surfaceDim: colors.surfaceDim.flutterColor,
        surfaceBright: colors.surfaceBright.flutterColor,
        surfaceContainerLowest: colors.surfaceContainerLowest.flutterColor,
        surfaceContainerLow: colors.surfaceContainerLow.flutterColor,
        surfaceContainer: colors.surfaceContainer.flutterColor,
        surfaceContainerHigh: colors.surfaceContainerHigh.flutterColor,
        surfaceContainerHighest: colors.surfaceContainerHighest.flutterColor,
        onSurfaceVariant: colors.onSurfaceVariant.flutterColor,
        outline: colors.outline.flutterColor,
        outlineVariant: colors.outlineVariant.flutterColor,
        shadow: colors.shadow.flutterColor,
        scrim: colors.scrim.flutterColor,
        inverseSurface: colors.inverseSurface.flutterColor,
        onInverseSurface: colors.onInverseSurface.flutterColor,
        inversePrimary: colors.inversePrimary.flutterColor,
        surfaceTint: colors.surfaceTint.flutterColor,
      );
  ThemeData toThemeData() => ThemeData(
      useMaterial3: true,
      colorScheme: toColorScheme(),
      extensions: [AuroraStatusColors.fromTokens(tokens)]);
}

/// Native status colors, including interpolation during Material theme changes.
class AuroraStatusColors extends ThemeExtension<AuroraStatusColors> {
  const AuroraStatusColors(
      {required this.success,
      required this.onSuccess,
      required this.successContainer,
      required this.onSuccessContainer,
      required this.warning,
      required this.onWarning,
      required this.warningContainer,
      required this.onWarningContainer,
      required this.info,
      required this.onInfo,
      required this.infoContainer,
      required this.onInfoContainer});
  factory AuroraStatusColors.fromTokens(AuroraTokens tokens) =>
      AuroraStatusColors(
          success: tokens.success.flutterColor,
          onSuccess: tokens.onSuccess.flutterColor,
          successContainer: tokens.successContainer.flutterColor,
          onSuccessContainer: tokens.onSuccessContainer.flutterColor,
          warning: tokens.warning.flutterColor,
          onWarning: tokens.onWarning.flutterColor,
          warningContainer: tokens.warningContainer.flutterColor,
          onWarningContainer: tokens.onWarningContainer.flutterColor,
          info: tokens.info.flutterColor,
          onInfo: tokens.onInfo.flutterColor,
          infoContainer: tokens.infoContainer.flutterColor,
          onInfoContainer: tokens.onInfoContainer.flutterColor);
  final Color success;
  final Color onSuccess;
  final Color successContainer;
  final Color onSuccessContainer;
  final Color warning;
  final Color onWarning;
  final Color warningContainer;
  final Color onWarningContainer;
  final Color info;
  final Color onInfo;
  final Color infoContainer;
  final Color onInfoContainer;
  @override
  AuroraStatusColors copyWith(
          {Color? success,
          Color? onSuccess,
          Color? successContainer,
          Color? onSuccessContainer,
          Color? warning,
          Color? onWarning,
          Color? warningContainer,
          Color? onWarningContainer,
          Color? info,
          Color? onInfo,
          Color? infoContainer,
          Color? onInfoContainer}) =>
      AuroraStatusColors(
          success: success ?? this.success,
          onSuccess: onSuccess ?? this.onSuccess,
          successContainer: successContainer ?? this.successContainer,
          onSuccessContainer: onSuccessContainer ?? this.onSuccessContainer,
          warning: warning ?? this.warning,
          onWarning: onWarning ?? this.onWarning,
          warningContainer: warningContainer ?? this.warningContainer,
          onWarningContainer: onWarningContainer ?? this.onWarningContainer,
          info: info ?? this.info,
          onInfo: onInfo ?? this.onInfo,
          infoContainer: infoContainer ?? this.infoContainer,
          onInfoContainer: onInfoContainer ?? this.onInfoContainer);
  @override
  AuroraStatusColors lerp(covariant AuroraStatusColors? other, double t) {
    if (other == null) return this;
    return AuroraStatusColors(
        success: Color.lerp(success, other.success, t)!,
        onSuccess: Color.lerp(onSuccess, other.onSuccess, t)!,
        successContainer:
            Color.lerp(successContainer, other.successContainer, t)!,
        onSuccessContainer:
            Color.lerp(onSuccessContainer, other.onSuccessContainer, t)!,
        warning: Color.lerp(warning, other.warning, t)!,
        onWarning: Color.lerp(onWarning, other.onWarning, t)!,
        warningContainer:
            Color.lerp(warningContainer, other.warningContainer, t)!,
        onWarningContainer:
            Color.lerp(onWarningContainer, other.onWarningContainer, t)!,
        info: Color.lerp(info, other.info, t)!,
        onInfo: Color.lerp(onInfo, other.onInfo, t)!,
        infoContainer: Color.lerp(infoContainer, other.infoContainer, t)!,
        onInfoContainer:
            Color.lerp(onInfoContainer, other.onInfoContainer, t)!);
  }
}
