// Generated by tools/generate_foundation.py. Edit that table, then regenerate.
import 'package:aurora/aurora.dart';
import 'package:flutter/material.dart';

extension AuroraFlutterColor on AuroraColor {
  Color get flutterColor => Color(argb);
}

/// Supplies every nondeprecated Material color role explicitly.
extension AuroraMaterialVariant on AuroraThemeVariant {
  ColorScheme toColorScheme() => ColorScheme(
        brightness: appearance == AuroraAppearance.light
            ? Brightness.light
            : Brightness.dark,
        primary: colors.primary.flutterColor,
        onPrimary: colors.onPrimary.flutterColor,
        primaryContainer: colors.primaryContainer.flutterColor,
        onPrimaryContainer: colors.onPrimaryContainer.flutterColor,
        primaryFixed: colors.primaryFixed.flutterColor,
        primaryFixedDim: colors.primaryFixedDim.flutterColor,
        onPrimaryFixed: colors.onPrimaryFixed.flutterColor,
        onPrimaryFixedVariant: colors.onPrimaryFixedVariant.flutterColor,
        secondary: colors.secondary.flutterColor,
        onSecondary: colors.onSecondary.flutterColor,
        secondaryContainer: colors.secondaryContainer.flutterColor,
        onSecondaryContainer: colors.onSecondaryContainer.flutterColor,
        secondaryFixed: colors.secondaryFixed.flutterColor,
        secondaryFixedDim: colors.secondaryFixedDim.flutterColor,
        onSecondaryFixed: colors.onSecondaryFixed.flutterColor,
        onSecondaryFixedVariant: colors.onSecondaryFixedVariant.flutterColor,
        tertiary: colors.tertiary.flutterColor,
        onTertiary: colors.onTertiary.flutterColor,
        tertiaryContainer: colors.tertiaryContainer.flutterColor,
        onTertiaryContainer: colors.onTertiaryContainer.flutterColor,
        tertiaryFixed: colors.tertiaryFixed.flutterColor,
        tertiaryFixedDim: colors.tertiaryFixedDim.flutterColor,
        onTertiaryFixed: colors.onTertiaryFixed.flutterColor,
        onTertiaryFixedVariant: colors.onTertiaryFixedVariant.flutterColor,
        error: colors.error.flutterColor,
        onError: colors.onError.flutterColor,
        errorContainer: colors.errorContainer.flutterColor,
        onErrorContainer: colors.onErrorContainer.flutterColor,
        surface: colors.surface.flutterColor,
        onSurface: colors.onSurface.flutterColor,
        surfaceDim: colors.surfaceDim.flutterColor,
        surfaceBright: colors.surfaceBright.flutterColor,
        surfaceContainerLowest: colors.surfaceContainerLowest.flutterColor,
        surfaceContainerLow: colors.surfaceContainerLow.flutterColor,
        surfaceContainer: colors.surfaceContainer.flutterColor,
        surfaceContainerHigh: colors.surfaceContainerHigh.flutterColor,
        surfaceContainerHighest: colors.surfaceContainerHighest.flutterColor,
        onSurfaceVariant: colors.onSurfaceVariant.flutterColor,
        outline: colors.outline.flutterColor,
        outlineVariant: colors.outlineVariant.flutterColor,
        shadow: colors.shadow.flutterColor,
        scrim: colors.scrim.flutterColor,
        inverseSurface: colors.inverseSurface.flutterColor,
        onInverseSurface: colors.onInverseSurface.flutterColor,
        inversePrimary: colors.inversePrimary.flutterColor,
        surfaceTint: colors.surfaceTint.flutterColor,
      );
  ThemeData toThemeData() =>
      ThemeData(useMaterial3: true, colorScheme: toColorScheme());
}
