import 'dart:convert';
import 'dart:io';
import '../../aurora.dart';

/// A target explicitly chosen by the CLI user, never supplied by a web request.
final class AuroraProject {
  AuroraProject._(this.root, this.importPackage);
  final Directory root;
  final String importPackage;

  static Future<AuroraProject> open(String path) async {
    final root = Directory(await Directory(path).resolveSymbolicLinks());
    final pubspec = File('${root.path}/pubspec.yaml');
    if (!await pubspec.exists())
      throw const FormatException('Project needs a pubspec.yaml');
    final content = await pubspec.readAsString();
    final adapter =
        RegExp(r'^\s+aurora_flutter\s*:', multiLine: true).hasMatch(content);
    final core = RegExp(r'^\s+aurora\s*:', multiLine: true).hasMatch(content);
    if (!adapter && !core)
      throw const FormatException(
          'Add an aurora or aurora_flutter dependency to the project first');
    return AuroraProject._(root, adapter ? 'aurora_flutter' : 'aurora');
  }

  Future<Map<String, Object?>> install(
      AuroraGenerationResult result, Map<String, dynamic> recipe) async {
    final id = result.theme.id;
    if (!RegExp(r'^[a-z][a-z0-9_-]{0,79}$').hasMatch(id)) {
      throw const FormatException(
          'Installation needs an ID of 1–80 lowercase letters, digits, underscores or hyphens, starting with a letter');
    }
    // Check each parent before creating anything. Never traverse project links.
    for (final path in ['${root.path}/lib', '${root.path}/lib/aurora_themes']) {
      final type = await FileSystemEntity.type(path, followLinks: false);
      if (type != FileSystemEntityType.notFound &&
          type != FileSystemEntityType.directory) {
        throw const FormatException(
            'Theme output parents must be ordinary directories');
      }
    }
    final parent = Directory('${root.path}/lib/aurora_themes');
    await parent.create(recursive: true);
    final target = Directory('${parent.path}/$id');
    if (await FileSystemEntity.type(target.path, followLinks: false) !=
        FileSystemEntityType.notFound) {
      throw FormatException(
          'Theme $id already exists. Choose a new ID; existing files are never overwritten');
    }
    final staging = await parent.createTemp('.aurora-');
    try {
      final encoder = const JsonEncoder.withIndent('  ');
      final files = <String, String>{
        'theme.json': encoder.convert(result.toJson()),
        'recipe.json': encoder.convert(recipe),
        for (final entry in result.theme.variants.entries)
          '${entry.key.name}.tokens.json':
              encoder.convert(AuroraDtcg.encode(entry.value)),
        'theme.dart': _source(result),
        'README.md':
            'Import theme.dart and call createAuroraTheme(contract: yourContract).\n'
                'Supply every required app extension in extensionValues for each appearance.\n'
                'Register the returned theme with your Aurora runtime/controller.\n',
      };
      for (final entry in files.entries) {
        await File('${staging.path}/${entry.key}')
            .writeAsString('${entry.value}\n');
      }
      // Recheck after preparing the bundle; do not replace a concurrent install.
      if (await FileSystemEntity.type(target.path, followLinks: false) !=
          FileSystemEntityType.notFound) {
        throw const FormatException('Theme destination already exists');
      }
      await staging.rename(target.path);
      return {
        'directory': target.path,
        'files': files.keys.toList(),
        'nextStep':
            'Import lib/aurora_themes/$id/theme.dart and register createAuroraTheme(contract: yourContract). Supply required app extensions through extensionValues.'
      };
    } finally {
      if (await staging.exists()) await staging.delete(recursive: true);
    }
  }

  String _source(AuroraGenerationResult result) {
    String literal(String value) => jsonEncode(value).replaceAll(r'$', r'\$');
    final theme = result.theme;
    return '''// Generated by Aurora. ${result.algorithm}
import 'package:$importPackage/$importPackage.dart';

/// Bind these foundation colors to your app's existing contract.
AuroraTheme createAuroraTheme({
  required AuroraContract contract,
  Map<AuroraAppearance, Map<AuroraColorToken, AuroraColor>> extensionValues = const {},
}) => AuroraTheme(
  id: ${literal(theme.id)},
  name: ${literal(theme.name)},
  preferredAppearance: AuroraAppearance.${theme.preferredAppearance.name},
  variants: [
${theme.variants.entries.map((entry) => '''    AuroraThemeVariant(
      contract: contract,
      appearance: AuroraAppearance.${entry.key.name},
      values: {
${entry.value.values.entries.map((value) => '        contract.tokens[${literal(value.key.path)}]!: AuroraColor.hex(${literal(value.value.hex)}),').join('\n')}
        ...?extensionValues[AuroraAppearance.${entry.key.name}],
      },
    ),''').join('\n')}
  ],
);
''';
  }
}
