// Generated by tools/generate_foundation.py. Edit that table, then regenerate.
import type { AuroraColor } from './color.js';
import { AuroraColorToken } from './token.js';
import type { AuroraThemeVariant } from './theme.js';

const primary = new AuroraColorToken('colors.primary', { description: "Accent for prominent actions." });
const onPrimary = new AuroraColorToken('colors.onPrimary', { description: "Text and icons on primary." });
const primaryContainer = new AuroraColorToken('colors.primaryContainer', { description: "Lower-emphasis container for prominent actions." });
const onPrimaryContainer = new AuroraColorToken('colors.onPrimaryContainer', { description: "Text and icons on primaryContainer." });
const primaryFixed = new AuroraColorToken('colors.primaryFixed', { description: "Container accent that stays constant across appearances." });
const primaryFixedDim = new AuroraColorToken('colors.primaryFixedDim', { description: "Stronger fixed primary accent." });
const onPrimaryFixed = new AuroraColorToken('colors.onPrimaryFixed', { description: "Text and icons on fixed primary accents." });
const onPrimaryFixedVariant = new AuroraColorToken('colors.onPrimaryFixedVariant', { description: "Lower-emphasis content on fixed primary accents." });
const secondary = new AuroraColorToken('colors.secondary', { description: "Accent for less prominent actions." });
const onSecondary = new AuroraColorToken('colors.onSecondary', { description: "Text and icons on secondary." });
const secondaryContainer = new AuroraColorToken('colors.secondaryContainer', { description: "Lower-emphasis container for less prominent actions." });
const onSecondaryContainer = new AuroraColorToken('colors.onSecondaryContainer', { description: "Text and icons on secondaryContainer." });
const secondaryFixed = new AuroraColorToken('colors.secondaryFixed', { description: "Container accent that stays constant across appearances." });
const secondaryFixedDim = new AuroraColorToken('colors.secondaryFixedDim', { description: "Stronger fixed secondary accent." });
const onSecondaryFixed = new AuroraColorToken('colors.onSecondaryFixed', { description: "Text and icons on fixed secondary accents." });
const onSecondaryFixedVariant = new AuroraColorToken('colors.onSecondaryFixedVariant', { description: "Lower-emphasis content on fixed secondary accents." });
const tertiary = new AuroraColorToken('colors.tertiary', { description: "Accent for contrasting accents." });
const onTertiary = new AuroraColorToken('colors.onTertiary', { description: "Text and icons on tertiary." });
const tertiaryContainer = new AuroraColorToken('colors.tertiaryContainer', { description: "Lower-emphasis container for contrasting accents." });
const onTertiaryContainer = new AuroraColorToken('colors.onTertiaryContainer', { description: "Text and icons on tertiaryContainer." });
const tertiaryFixed = new AuroraColorToken('colors.tertiaryFixed', { description: "Container accent that stays constant across appearances." });
const tertiaryFixedDim = new AuroraColorToken('colors.tertiaryFixedDim', { description: "Stronger fixed tertiary accent." });
const onTertiaryFixed = new AuroraColorToken('colors.onTertiaryFixed', { description: "Text and icons on fixed tertiary accents." });
const onTertiaryFixedVariant = new AuroraColorToken('colors.onTertiaryFixedVariant', { description: "Lower-emphasis content on fixed tertiary accents." });
const error = new AuroraColorToken('colors.error', { description: "Error and destructive feedback." });
const onError = new AuroraColorToken('colors.onError', { description: "Text and icons on error." });
const errorContainer = new AuroraColorToken('colors.errorContainer', { description: "Lower-emphasis error container." });
const onErrorContainer = new AuroraColorToken('colors.onErrorContainer', { description: "Text and icons on errorContainer." });
const surface = new AuroraColorToken('colors.surface', { description: "Default page and component surface." });
const onSurface = new AuroraColorToken('colors.onSurface', { description: "Primary text and icons on surfaces." });
const surfaceDim = new AuroraColorToken('colors.surfaceDim', { description: "Dimmest surface tone." });
const surfaceBright = new AuroraColorToken('colors.surfaceBright', { description: "Brightest surface tone." });
const surfaceContainerLowest = new AuroraColorToken('colors.surfaceContainerLowest', { description: "Lowest surface container level." });
const surfaceContainerLow = new AuroraColorToken('colors.surfaceContainerLow', { description: "Low surface container level." });
const surfaceContainer = new AuroraColorToken('colors.surfaceContainer', { description: "Default distinct surface container." });
const surfaceContainerHigh = new AuroraColorToken('colors.surfaceContainerHigh', { description: "High surface container level." });
const surfaceContainerHighest = new AuroraColorToken('colors.surfaceContainerHighest', { description: "Highest surface container level." });
const onSurfaceVariant = new AuroraColorToken('colors.onSurfaceVariant', { description: "Lower-emphasis text and icons on surfaces." });
const outline = new AuroraColorToken('colors.outline', { description: "Boundaries requiring emphasis." });
const outlineVariant = new AuroraColorToken('colors.outlineVariant', { description: "Subtle decorative boundaries and dividers." });
const shadow = new AuroraColorToken('colors.shadow', { description: "Color of cast shadows." });
const scrim = new AuroraColorToken('colors.scrim', { description: "Color of obscuring modal overlays." });
const inverseSurface = new AuroraColorToken('colors.inverseSurface', { description: "Surface contrasting with surrounding appearance." });
const onInverseSurface = new AuroraColorToken('colors.onInverseSurface', { description: "Text and icons on inverseSurface." });
const inversePrimary = new AuroraColorToken('colors.inversePrimary', { description: "Primary accent on inverseSurface." });
const surfaceTint = new AuroraColorToken('colors.surfaceTint', { description: "Accent used by Material surface tint treatments." });
const success = new AuroraColorToken('colors.success', { description: "Success feedback." });
const onSuccess = new AuroraColorToken('colors.onSuccess', { description: "Text and icons on success." });
const successContainer = new AuroraColorToken('colors.successContainer', { description: "Lower-emphasis success container." });
const onSuccessContainer = new AuroraColorToken('colors.onSuccessContainer', { description: "Text and icons on successContainer." });
const warning = new AuroraColorToken('colors.warning', { description: "Warning feedback." });
const onWarning = new AuroraColorToken('colors.onWarning', { description: "Text and icons on warning." });
const warningContainer = new AuroraColorToken('colors.warningContainer', { description: "Lower-emphasis warning container." });
const onWarningContainer = new AuroraColorToken('colors.onWarningContainer', { description: "Text and icons on warningContainer." });
const info = new AuroraColorToken('colors.info', { description: "Info feedback." });
const onInfo = new AuroraColorToken('colors.onInfo', { description: "Text and icons on info." });
const infoContainer = new AuroraColorToken('colors.infoContainer', { description: "Lower-emphasis info container." });
const onInfoContainer = new AuroraColorToken('colors.onInfoContainer', { description: "Text and icons on infoContainer." });

/** Aurora foundation v1: current Material color roles plus status roles. */
export const AuroraFoundation = Object.freeze({
  version: 1 as const,
  primary,
  onPrimary,
  primaryContainer,
  onPrimaryContainer,
  primaryFixed,
  primaryFixedDim,
  onPrimaryFixed,
  onPrimaryFixedVariant,
  secondary,
  onSecondary,
  secondaryContainer,
  onSecondaryContainer,
  secondaryFixed,
  secondaryFixedDim,
  onSecondaryFixed,
  onSecondaryFixedVariant,
  tertiary,
  onTertiary,
  tertiaryContainer,
  onTertiaryContainer,
  tertiaryFixed,
  tertiaryFixedDim,
  onTertiaryFixed,
  onTertiaryFixedVariant,
  error,
  onError,
  errorContainer,
  onErrorContainer,
  surface,
  onSurface,
  surfaceDim,
  surfaceBright,
  surfaceContainerLowest,
  surfaceContainerLow,
  surfaceContainer,
  surfaceContainerHigh,
  surfaceContainerHighest,
  onSurfaceVariant,
  outline,
  outlineVariant,
  shadow,
  scrim,
  inverseSurface,
  onInverseSurface,
  inversePrimary,
  surfaceTint,
  success,
  onSuccess,
  successContainer,
  onSuccessContainer,
  warning,
  onWarning,
  warningContainer,
  onWarningContainer,
  info,
  onInfo,
  infoContainer,
  onInfoContainer,
  tokens: Object.freeze([
    primary,
    onPrimary,
    primaryContainer,
    onPrimaryContainer,
    primaryFixed,
    primaryFixedDim,
    onPrimaryFixed,
    onPrimaryFixedVariant,
    secondary,
    onSecondary,
    secondaryContainer,
    onSecondaryContainer,
    secondaryFixed,
    secondaryFixedDim,
    onSecondaryFixed,
    onSecondaryFixedVariant,
    tertiary,
    onTertiary,
    tertiaryContainer,
    onTertiaryContainer,
    tertiaryFixed,
    tertiaryFixedDim,
    onTertiaryFixed,
    onTertiaryFixedVariant,
    error,
    onError,
    errorContainer,
    onErrorContainer,
    surface,
    onSurface,
    surfaceDim,
    surfaceBright,
    surfaceContainerLowest,
    surfaceContainerLow,
    surfaceContainer,
    surfaceContainerHigh,
    surfaceContainerHighest,
    onSurfaceVariant,
    outline,
    outlineVariant,
    shadow,
    scrim,
    inverseSurface,
    onInverseSurface,
    inversePrimary,
    surfaceTint,
    success,
    onSuccess,
    successContainer,
    onSuccessContainer,
    warning,
    onWarning,
    warningContainer,
    onWarningContainer,
    info,
    onInfo,
    infoContainer,
    onInfoContainer,
  ]) as readonly AuroraColorToken[],
});

/** Direct immutable values for the entire app contract. No global active theme. */
export class AuroraTokens {
  constructor(private readonly variant: AuroraThemeVariant) {}

  read(token: AuroraColorToken): AuroraColor {
    return this.variant.read(token);
  }

  /** Accent for prominent actions. */
  get primary(): AuroraColor {
    return this.variant.read(primary);
  }

  /** Text and icons on primary. */
  get onPrimary(): AuroraColor {
    return this.variant.read(onPrimary);
  }

  /** Lower-emphasis container for prominent actions. */
  get primaryContainer(): AuroraColor {
    return this.variant.read(primaryContainer);
  }

  /** Text and icons on primaryContainer. */
  get onPrimaryContainer(): AuroraColor {
    return this.variant.read(onPrimaryContainer);
  }

  /** Container accent that stays constant across appearances. */
  get primaryFixed(): AuroraColor {
    return this.variant.read(primaryFixed);
  }

  /** Stronger fixed primary accent. */
  get primaryFixedDim(): AuroraColor {
    return this.variant.read(primaryFixedDim);
  }

  /** Text and icons on fixed primary accents. */
  get onPrimaryFixed(): AuroraColor {
    return this.variant.read(onPrimaryFixed);
  }

  /** Lower-emphasis content on fixed primary accents. */
  get onPrimaryFixedVariant(): AuroraColor {
    return this.variant.read(onPrimaryFixedVariant);
  }

  /** Accent for less prominent actions. */
  get secondary(): AuroraColor {
    return this.variant.read(secondary);
  }

  /** Text and icons on secondary. */
  get onSecondary(): AuroraColor {
    return this.variant.read(onSecondary);
  }

  /** Lower-emphasis container for less prominent actions. */
  get secondaryContainer(): AuroraColor {
    return this.variant.read(secondaryContainer);
  }

  /** Text and icons on secondaryContainer. */
  get onSecondaryContainer(): AuroraColor {
    return this.variant.read(onSecondaryContainer);
  }

  /** Container accent that stays constant across appearances. */
  get secondaryFixed(): AuroraColor {
    return this.variant.read(secondaryFixed);
  }

  /** Stronger fixed secondary accent. */
  get secondaryFixedDim(): AuroraColor {
    return this.variant.read(secondaryFixedDim);
  }

  /** Text and icons on fixed secondary accents. */
  get onSecondaryFixed(): AuroraColor {
    return this.variant.read(onSecondaryFixed);
  }

  /** Lower-emphasis content on fixed secondary accents. */
  get onSecondaryFixedVariant(): AuroraColor {
    return this.variant.read(onSecondaryFixedVariant);
  }

  /** Accent for contrasting accents. */
  get tertiary(): AuroraColor {
    return this.variant.read(tertiary);
  }

  /** Text and icons on tertiary. */
  get onTertiary(): AuroraColor {
    return this.variant.read(onTertiary);
  }

  /** Lower-emphasis container for contrasting accents. */
  get tertiaryContainer(): AuroraColor {
    return this.variant.read(tertiaryContainer);
  }

  /** Text and icons on tertiaryContainer. */
  get onTertiaryContainer(): AuroraColor {
    return this.variant.read(onTertiaryContainer);
  }

  /** Container accent that stays constant across appearances. */
  get tertiaryFixed(): AuroraColor {
    return this.variant.read(tertiaryFixed);
  }

  /** Stronger fixed tertiary accent. */
  get tertiaryFixedDim(): AuroraColor {
    return this.variant.read(tertiaryFixedDim);
  }

  /** Text and icons on fixed tertiary accents. */
  get onTertiaryFixed(): AuroraColor {
    return this.variant.read(onTertiaryFixed);
  }

  /** Lower-emphasis content on fixed tertiary accents. */
  get onTertiaryFixedVariant(): AuroraColor {
    return this.variant.read(onTertiaryFixedVariant);
  }

  /** Error and destructive feedback. */
  get error(): AuroraColor {
    return this.variant.read(error);
  }

  /** Text and icons on error. */
  get onError(): AuroraColor {
    return this.variant.read(onError);
  }

  /** Lower-emphasis error container. */
  get errorContainer(): AuroraColor {
    return this.variant.read(errorContainer);
  }

  /** Text and icons on errorContainer. */
  get onErrorContainer(): AuroraColor {
    return this.variant.read(onErrorContainer);
  }

  /** Default page and component surface. */
  get surface(): AuroraColor {
    return this.variant.read(surface);
  }

  /** Primary text and icons on surfaces. */
  get onSurface(): AuroraColor {
    return this.variant.read(onSurface);
  }

  /** Dimmest surface tone. */
  get surfaceDim(): AuroraColor {
    return this.variant.read(surfaceDim);
  }

  /** Brightest surface tone. */
  get surfaceBright(): AuroraColor {
    return this.variant.read(surfaceBright);
  }

  /** Lowest surface container level. */
  get surfaceContainerLowest(): AuroraColor {
    return this.variant.read(surfaceContainerLowest);
  }

  /** Low surface container level. */
  get surfaceContainerLow(): AuroraColor {
    return this.variant.read(surfaceContainerLow);
  }

  /** Default distinct surface container. */
  get surfaceContainer(): AuroraColor {
    return this.variant.read(surfaceContainer);
  }

  /** High surface container level. */
  get surfaceContainerHigh(): AuroraColor {
    return this.variant.read(surfaceContainerHigh);
  }

  /** Highest surface container level. */
  get surfaceContainerHighest(): AuroraColor {
    return this.variant.read(surfaceContainerHighest);
  }

  /** Lower-emphasis text and icons on surfaces. */
  get onSurfaceVariant(): AuroraColor {
    return this.variant.read(onSurfaceVariant);
  }

  /** Boundaries requiring emphasis. */
  get outline(): AuroraColor {
    return this.variant.read(outline);
  }

  /** Subtle decorative boundaries and dividers. */
  get outlineVariant(): AuroraColor {
    return this.variant.read(outlineVariant);
  }

  /** Color of cast shadows. */
  get shadow(): AuroraColor {
    return this.variant.read(shadow);
  }

  /** Color of obscuring modal overlays. */
  get scrim(): AuroraColor {
    return this.variant.read(scrim);
  }

  /** Surface contrasting with surrounding appearance. */
  get inverseSurface(): AuroraColor {
    return this.variant.read(inverseSurface);
  }

  /** Text and icons on inverseSurface. */
  get onInverseSurface(): AuroraColor {
    return this.variant.read(onInverseSurface);
  }

  /** Primary accent on inverseSurface. */
  get inversePrimary(): AuroraColor {
    return this.variant.read(inversePrimary);
  }

  /** Accent used by Material surface tint treatments. */
  get surfaceTint(): AuroraColor {
    return this.variant.read(surfaceTint);
  }

  /** Success feedback. */
  get success(): AuroraColor {
    return this.variant.read(success);
  }

  /** Text and icons on success. */
  get onSuccess(): AuroraColor {
    return this.variant.read(onSuccess);
  }

  /** Lower-emphasis success container. */
  get successContainer(): AuroraColor {
    return this.variant.read(successContainer);
  }

  /** Text and icons on successContainer. */
  get onSuccessContainer(): AuroraColor {
    return this.variant.read(onSuccessContainer);
  }

  /** Warning feedback. */
  get warning(): AuroraColor {
    return this.variant.read(warning);
  }

  /** Text and icons on warning. */
  get onWarning(): AuroraColor {
    return this.variant.read(onWarning);
  }

  /** Lower-emphasis warning container. */
  get warningContainer(): AuroraColor {
    return this.variant.read(warningContainer);
  }

  /** Text and icons on warningContainer. */
  get onWarningContainer(): AuroraColor {
    return this.variant.read(onWarningContainer);
  }

  /** Info feedback. */
  get info(): AuroraColor {
    return this.variant.read(info);
  }

  /** Text and icons on info. */
  get onInfo(): AuroraColor {
    return this.variant.read(onInfo);
  }

  /** Lower-emphasis info container. */
  get infoContainer(): AuroraColor {
    return this.variant.read(infoContainer);
  }

  /** Text and icons on infoContainer. */
  get onInfoContainer(): AuroraColor {
    return this.variant.read(onInfoContainer);
  }
}
