// Generated by tools/generate_foundation.py. Edit that table, then regenerate.
// Source: spec/texture-foundation-v1.json, exported from the Dart texture foundation.
import { AuroraAlias, AuroraLiteral } from './ref.js';
import {
  AuroraCubicBezierToken,
  AuroraDimensionToken,
  AuroraDurationToken,
  AuroraFontFamilyToken,
  AuroraTypographyToken,
  type AuroraToken,
} from './token.js';
import {
  AuroraCubicBezier,
  AuroraDimension,
  AuroraDuration,
  AuroraFontFamily,
  AuroraFontWeight,
  AuroraTypography,
} from './values.js';

const brandFamily = new AuroraFontFamilyToken("type.family.brand", {
  description: "Expressive typeface for display and headline text.",
});
const plainFamily = new AuroraFontFamilyToken("type.family.plain", {
  description: "Readable typeface for titles, body and labels.",
});
const displayLarge = new AuroraTypographyToken("type.displayLarge", {
  description: "Largest display text, for short hero numbers or words.",
});
const displayMedium = new AuroraTypographyToken("type.displayMedium", {
  description: "Medium display text.",
});
const displaySmall = new AuroraTypographyToken("type.displaySmall", {
  description: "Small display text.",
});
const headlineLarge = new AuroraTypographyToken("type.headlineLarge", {
  description: "Large headlines on prominent screens.",
});
const headlineMedium = new AuroraTypographyToken("type.headlineMedium", {
  description: "Medium headlines.",
});
const headlineSmall = new AuroraTypographyToken("type.headlineSmall", {
  description: "Small headlines.",
});
const titleLarge = new AuroraTypographyToken("type.titleLarge", {
  description: "Large titles, such as app bar titles.",
});
const titleMedium = new AuroraTypographyToken("type.titleMedium", {
  description: "Medium titles, such as list headers.",
});
const titleSmall = new AuroraTypographyToken("type.titleSmall", {
  description: "Small titles.",
});
const bodyLarge = new AuroraTypographyToken("type.bodyLarge", {
  description: "Large body text.",
});
const bodyMedium = new AuroraTypographyToken("type.bodyMedium", {
  description: "Default body text.",
});
const bodySmall = new AuroraTypographyToken("type.bodySmall", {
  description: "Small body text, such as captions.",
});
const labelLarge = new AuroraTypographyToken("type.labelLarge", {
  description: "Large labels, such as button text.",
});
const labelMedium = new AuroraTypographyToken("type.labelMedium", {
  description: "Medium labels.",
});
const labelSmall = new AuroraTypographyToken("type.labelSmall", {
  description: "Small labels, such as badges.",
});
const extraSmallShape = new AuroraDimensionToken("shape.extraSmall", {
  description: "Corner radius for small elements such as text fields and menus.",
});
const smallShape = new AuroraDimensionToken("shape.small", {
  description: "Corner radius for chips and small cards.",
});
const mediumShape = new AuroraDimensionToken("shape.medium", {
  description: "Corner radius for cards.",
});
const largeShape = new AuroraDimensionToken("shape.large", {
  description: "Corner radius for large surfaces such as navigation drawers.",
});
const extraLargeShape = new AuroraDimensionToken("shape.extraLarge", {
  description: "Corner radius for dialogs and sheets.",
});
const shortDuration = new AuroraDurationToken("motion.short", {
  description: "Duration of small, quick transitions such as selection changes.",
});
const mediumDuration = new AuroraDurationToken("motion.medium", {
  description: "Duration of standard transitions.",
});
const longDuration = new AuroraDurationToken("motion.long", {
  description: "Duration of large transitions such as full-screen changes.",
});
const extraLongDuration = new AuroraDurationToken("motion.extraLong", {
  description: "Duration of slow, emphasized transitions.",
});
const easingStandard = new AuroraCubicBezierToken("motion.easing.standard", {
  description: "Easing for transitions that begin and end on screen.",
});
const easingEmphasizedDecelerate = new AuroraCubicBezierToken("motion.easing.emphasizedDecelerate", {
  description: "Easing for elements entering the screen.",
});
const easingEmphasizedAccelerate = new AuroraCubicBezierToken("motion.easing.emphasizedAccelerate", {
  description: "Easing for elements leaving the screen.",
});

/**
 * Aurora texture foundation v1: the Material 3 baseline type scale, corner
 * shapes and motion. Every texture supplies these; apps add their own tokens as
 * texture contract extensions. The `type`, `shape` and `motion` namespaces are
 * reserved.
 */
export const AuroraTextureFoundation = Object.freeze({
  version: 1 as const,
  namespaces: Object.freeze(["type", "shape", "motion"]) as readonly string[],
  brandFamily,
  plainFamily,
  displayLarge,
  displayMedium,
  displaySmall,
  headlineLarge,
  headlineMedium,
  headlineSmall,
  titleLarge,
  titleMedium,
  titleSmall,
  bodyLarge,
  bodyMedium,
  bodySmall,
  labelLarge,
  labelMedium,
  labelSmall,
  extraSmallShape,
  smallShape,
  mediumShape,
  largeShape,
  extraLargeShape,
  shortDuration,
  mediumDuration,
  longDuration,
  extraLongDuration,
  easingStandard,
  easingEmphasizedDecelerate,
  easingEmphasizedAccelerate,
  tokens: Object.freeze([
    brandFamily,
    plainFamily,
    displayLarge,
    displayMedium,
    displaySmall,
    headlineLarge,
    headlineMedium,
    headlineSmall,
    titleLarge,
    titleMedium,
    titleSmall,
    bodyLarge,
    bodyMedium,
    bodySmall,
    labelLarge,
    labelMedium,
    labelSmall,
    extraSmallShape,
    smallShape,
    mediumShape,
    largeShape,
    extraLargeShape,
    shortDuration,
    mediumDuration,
    longDuration,
    extraLongDuration,
    easingStandard,
    easingEmphasizedDecelerate,
    easingEmphasizedAccelerate,
  ]) as readonly AuroraToken<unknown>[],
});

/** Material 3 baseline values for every texture foundation token. */
export const auroraMaterialTextureValues: ReadonlyMap<AuroraToken<unknown>, unknown> = new Map<
  AuroraToken<unknown>,
  unknown
>([
  [
    brandFamily,
    new AuroraFontFamily(["Roboto"]),
  ],
  [
    plainFamily,
    new AuroraFontFamily(["Roboto"]),
  ],
  [
    displayLarge,
    new AuroraTypography({
      fontFamily: new AuroraAlias(brandFamily),
      fontSize: AuroraDimension.dp(57.0),
      fontWeight: new AuroraFontWeight(400),
      letterSpacing: AuroraDimension.dp(-0.25),
      lineHeight: new AuroraLiteral(1.1228070175438596),
    }),
  ],
  [
    displayMedium,
    new AuroraTypography({
      fontFamily: new AuroraAlias(brandFamily),
      fontSize: AuroraDimension.dp(45.0),
      fontWeight: new AuroraFontWeight(400),
      letterSpacing: AuroraDimension.dp(0.0),
      lineHeight: new AuroraLiteral(1.1555555555555554),
    }),
  ],
  [
    displaySmall,
    new AuroraTypography({
      fontFamily: new AuroraAlias(brandFamily),
      fontSize: AuroraDimension.dp(36.0),
      fontWeight: new AuroraFontWeight(400),
      letterSpacing: AuroraDimension.dp(0.0),
      lineHeight: new AuroraLiteral(1.2222222222222223),
    }),
  ],
  [
    headlineLarge,
    new AuroraTypography({
      fontFamily: new AuroraAlias(brandFamily),
      fontSize: AuroraDimension.dp(32.0),
      fontWeight: new AuroraFontWeight(400),
      letterSpacing: AuroraDimension.dp(0.0),
      lineHeight: new AuroraLiteral(1.25),
    }),
  ],
  [
    headlineMedium,
    new AuroraTypography({
      fontFamily: new AuroraAlias(brandFamily),
      fontSize: AuroraDimension.dp(28.0),
      fontWeight: new AuroraFontWeight(400),
      letterSpacing: AuroraDimension.dp(0.0),
      lineHeight: new AuroraLiteral(1.2857142857142858),
    }),
  ],
  [
    headlineSmall,
    new AuroraTypography({
      fontFamily: new AuroraAlias(brandFamily),
      fontSize: AuroraDimension.dp(24.0),
      fontWeight: new AuroraFontWeight(400),
      letterSpacing: AuroraDimension.dp(0.0),
      lineHeight: new AuroraLiteral(1.3333333333333333),
    }),
  ],
  [
    titleLarge,
    new AuroraTypography({
      fontFamily: new AuroraAlias(plainFamily),
      fontSize: AuroraDimension.dp(22.0),
      fontWeight: new AuroraFontWeight(400),
      letterSpacing: AuroraDimension.dp(0.0),
      lineHeight: new AuroraLiteral(1.2727272727272727),
    }),
  ],
  [
    titleMedium,
    new AuroraTypography({
      fontFamily: new AuroraAlias(plainFamily),
      fontSize: AuroraDimension.dp(16.0),
      fontWeight: new AuroraFontWeight(500),
      letterSpacing: AuroraDimension.dp(0.15),
      lineHeight: new AuroraLiteral(1.5),
    }),
  ],
  [
    titleSmall,
    new AuroraTypography({
      fontFamily: new AuroraAlias(plainFamily),
      fontSize: AuroraDimension.dp(14.0),
      fontWeight: new AuroraFontWeight(500),
      letterSpacing: AuroraDimension.dp(0.1),
      lineHeight: new AuroraLiteral(1.4285714285714286),
    }),
  ],
  [
    bodyLarge,
    new AuroraTypography({
      fontFamily: new AuroraAlias(plainFamily),
      fontSize: AuroraDimension.dp(16.0),
      fontWeight: new AuroraFontWeight(400),
      letterSpacing: AuroraDimension.dp(0.5),
      lineHeight: new AuroraLiteral(1.5),
    }),
  ],
  [
    bodyMedium,
    new AuroraTypography({
      fontFamily: new AuroraAlias(plainFamily),
      fontSize: AuroraDimension.dp(14.0),
      fontWeight: new AuroraFontWeight(400),
      letterSpacing: AuroraDimension.dp(0.25),
      lineHeight: new AuroraLiteral(1.4285714285714286),
    }),
  ],
  [
    bodySmall,
    new AuroraTypography({
      fontFamily: new AuroraAlias(plainFamily),
      fontSize: AuroraDimension.dp(12.0),
      fontWeight: new AuroraFontWeight(400),
      letterSpacing: AuroraDimension.dp(0.4),
      lineHeight: new AuroraLiteral(1.3333333333333333),
    }),
  ],
  [
    labelLarge,
    new AuroraTypography({
      fontFamily: new AuroraAlias(plainFamily),
      fontSize: AuroraDimension.dp(14.0),
      fontWeight: new AuroraFontWeight(500),
      letterSpacing: AuroraDimension.dp(0.1),
      lineHeight: new AuroraLiteral(1.4285714285714286),
    }),
  ],
  [
    labelMedium,
    new AuroraTypography({
      fontFamily: new AuroraAlias(plainFamily),
      fontSize: AuroraDimension.dp(12.0),
      fontWeight: new AuroraFontWeight(500),
      letterSpacing: AuroraDimension.dp(0.5),
      lineHeight: new AuroraLiteral(1.3333333333333333),
    }),
  ],
  [
    labelSmall,
    new AuroraTypography({
      fontFamily: new AuroraAlias(plainFamily),
      fontSize: AuroraDimension.dp(11.0),
      fontWeight: new AuroraFontWeight(500),
      letterSpacing: AuroraDimension.dp(0.5),
      lineHeight: new AuroraLiteral(1.4545454545454546),
    }),
  ],
  [
    extraSmallShape,
    AuroraDimension.dp(4.0),
  ],
  [
    smallShape,
    AuroraDimension.dp(8.0),
  ],
  [
    mediumShape,
    AuroraDimension.dp(12.0),
  ],
  [
    largeShape,
    AuroraDimension.dp(16.0),
  ],
  [
    extraLargeShape,
    AuroraDimension.dp(28.0),
  ],
  [
    shortDuration,
    AuroraDuration.ms(100.0),
  ],
  [
    mediumDuration,
    AuroraDuration.ms(300.0),
  ],
  [
    longDuration,
    AuroraDuration.ms(500.0),
  ],
  [
    extraLongDuration,
    AuroraDuration.ms(800.0),
  ],
  [
    easingStandard,
    new AuroraCubicBezier(0.2, 0.0, 0.0, 1.0),
  ],
  [
    easingEmphasizedDecelerate,
    new AuroraCubicBezier(0.05, 0.7, 0.1, 1.0),
  ],
  [
    easingEmphasizedAccelerate,
    new AuroraCubicBezier(0.3, 0.0, 0.8, 0.15),
  ],
]);
