"""Regenerate checked-in foundation accessors and Flutter mapping from one table.

This is repository maintenance tooling, not Aurora's future theme generator.
Run from any directory: python tools/generate_foundation.py
"""
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
ROWS = []

def add(name, description, light, dark):
    ROWS.append((name, description, light, dark))

for name, label, light, dark in [
    ('primary', 'prominent actions', ['6750a4', 'ffffff', 'eaddff', '21005d'], ['d0bcff', '381e72', '4f378b', 'eaddff']),
    ('secondary', 'less prominent actions', ['625b71', 'ffffff', 'e8def8', '1d192b'], ['ccc2dc', '332d41', '4a4458', 'e8def8']),
    ('tertiary', 'contrasting accents', ['7d5260', 'ffffff', 'ffd8e4', '31111d'], ['efb8c8', '492532', '633b48', 'ffd8e4']),
]:
    cap = name.capitalize()
    add(name, f'Accent for {label}.', light[0], dark[0])
    add('on' + cap, f'Text and icons on {name}.', light[1], dark[1])
    add(name + 'Container', f'Lower-emphasis container for {label}.', light[2], dark[2])
    add('on' + cap + 'Container', f'Text and icons on {name}Container.', light[3], dark[3])
    add(name + 'Fixed', f'Container accent that stays constant across appearances.', light[2], light[2])
    add(name + 'FixedDim', f'Stronger fixed {name} accent.', dark[0], dark[0])
    add('on' + cap + 'Fixed', f'Text and icons on fixed {name} accents.', light[3], light[3])
    add('on' + cap + 'FixedVariant', f'Lower-emphasis content on fixed {name} accents.', dark[2], dark[2])

for name, description, light, dark in [
    ('error', 'Error and destructive feedback.', 'b3261e', 'f2b8b5'),
    ('onError', 'Text and icons on error.', 'ffffff', '601410'),
    ('errorContainer', 'Lower-emphasis error container.', 'f9dedc', '8c1d18'),
    ('onErrorContainer', 'Text and icons on errorContainer.', '410e0b', 'f9dedc'),
    ('surface', 'Default page and component surface.', 'fffbfe', '141218'),
    ('onSurface', 'Primary text and icons on surfaces.', '1c1b1f', 'e6e0e9'),
    ('surfaceDim', 'Dimmest surface tone.', 'ded8e1', '141218'),
    ('surfaceBright', 'Brightest surface tone.', 'fffbfe', '3b383e'),
    ('surfaceContainerLowest', 'Lowest surface container level.', 'ffffff', '0f0d13'),
    ('surfaceContainerLow', 'Low surface container level.', 'f7f2fa', '1d1b20'),
    ('surfaceContainer', 'Default distinct surface container.', 'f3edf7', '211f26'),
    ('surfaceContainerHigh', 'High surface container level.', 'ece6f0', '2b2930'),
    ('surfaceContainerHighest', 'Highest surface container level.', 'e6e0e9', '36343b'),
    ('onSurfaceVariant', 'Lower-emphasis text and icons on surfaces.', '49454f', 'cac4d0'),
    ('outline', 'Boundaries requiring emphasis.', '79747e', '938f99'),
    ('outlineVariant', 'Subtle decorative boundaries and dividers.', 'cac4d0', '49454f'),
    ('shadow', 'Color of cast shadows.', '000000', '000000'),
    ('scrim', 'Color of obscuring modal overlays.', '000000', '000000'),
    ('inverseSurface', 'Surface contrasting with surrounding appearance.', '313033', 'e6e0e9'),
    ('onInverseSurface', 'Text and icons on inverseSurface.', 'f4eff4', '313033'),
    ('inversePrimary', 'Primary accent on inverseSurface.', 'd0bcff', '6750a4'),
    ('surfaceTint', 'Accent used by Material surface tint treatments.', '6750a4', 'd0bcff'),
]:
    add(name, description, light, dark)

MATERIAL = [r[0] for r in ROWS]
for name, light, dark in [
    ('success', ['146c2e', 'ffffff', 'a6f5b0', '002108'], ['8bd996', '003915', '005321', 'a6f5b0']),
    ('warning', ['805600', 'ffffff', 'ffdea6', '281900'], ['f4bf60', '442c00', '614000', 'ffdea6']),
    ('info', ['0061a4', 'ffffff', 'd1e4ff', '001d36'], ['9ecaff', '003258', '00497d', 'd1e4ff']),
]:
    cap = name.capitalize()
    for token, description, index in [
        (name, f'{cap} feedback.', 0),
        ('on' + cap, f'Text and icons on {name}.', 1),
        (name + 'Container', f'Lower-emphasis {name} container.', 2),
        ('on' + cap + 'Container', f'Text and icons on {name}Container.', 3),
    ]:
        add(token, description, light[index], dark[index])

header = '// Generated by tools/generate_foundation.py. Edit that table, then regenerate.\n'
foundation = header + "import 'color.dart';\nimport 'contract.dart';\nimport 'theme.dart';\n\n"
foundation += '/// Aurora foundation v1: current Material color roles plus status roles.\nabstract final class AuroraFoundation {\n  static const version = 1;\n'
for name, desc, _, _ in ROWS:
    foundation += f"  static const {name} = AuroraColorToken('colors.{name}', description: '{desc}');\n"
foundation += '  static const tokens = <AuroraColorToken>[\n' + ''.join(f'    {r[0]},\n' for r in ROWS) + '  ];\n}\n\n'
foundation += '/// Direct immutable values for the entire app contract. No global active theme.\nfinal class AuroraTokens {\n  const AuroraTokens(this._variant);\n  final AuroraThemeVariant _variant;\n  AuroraColor read(AuroraColorToken token) => _variant.read(token);\n'
for name, *_ in ROWS:
    foundation += f'  AuroraColor get {name} => _variant.read(AuroraFoundation.{name});\n'
foundation += '}\n'
(ROOT / 'packages/aurora/lib/src/foundation.dart').write_text(foundation, encoding='utf-8')

starters = header + "import 'color.dart';\nimport 'contract.dart';\nimport 'foundation.dart';\nimport 'theme.dart';\n\n"
starters += '/// Complete explicit foundation presets; app extensions are still required.\nabstract final class AuroraStarter {\n'
for appearance, index in [('light', 2), ('dark', 3)]:
    starters += f'  static final Map<AuroraColorToken, AuroraColor> {appearance} = Map.unmodifiable({{\n'
    for row in ROWS:
        starters += f"    AuroraFoundation.{row[0]}: AuroraColor.hex('#{row[index]}'),\n"
    starters += '  });\n'
starters += '''  static AuroraThemeVariant variant({
    required AuroraContract contract,
    required AuroraAppearance appearance,
    Map<AuroraColorToken, AuroraColor> values = const {},
  }) => AuroraThemeVariant(
    contract: contract,
    appearance: appearance,
    values: {...(appearance == AuroraAppearance.light ? light : dark), ...values},
  );
}
'''
(ROOT / 'packages/aurora/lib/src/starters.dart').write_text(starters, encoding='utf-8')

mapping = header + "import 'package:aurora/aurora.dart';\nimport 'package:flutter/material.dart';\n\n"
mapping += '''extension AuroraFlutterColor on AuroraColor {
  Color get flutterColor => Color(argb);
}

/// Supplies every nondeprecated Material color role explicitly.
extension AuroraMaterialVariant on AuroraThemeVariant {
  ColorScheme toColorScheme() => ColorScheme(
    brightness: appearance == AuroraAppearance.light ? Brightness.light : Brightness.dark,
'''
mapping += ''.join(f'    {name}: colors.{name}.flutterColor,\n' for name in MATERIAL)
mapping += '  );\n  ThemeData toThemeData() => ThemeData(useMaterial3: true, colorScheme: toColorScheme(), extensions: [AuroraStatusColors.fromTokens(tokens)]);\n}\n'
status_names = [name for name, *_ in ROWS if name not in MATERIAL]
mapping += '\n/// Native status colors, including interpolation during Material theme changes.\nclass AuroraStatusColors extends ThemeExtension<AuroraStatusColors> {\n'
mapping += '  const AuroraStatusColors({' + ', '.join(f'required this.{name}' for name in status_names) + '});\n'
mapping += '  factory AuroraStatusColors.fromTokens(AuroraTokens tokens) => AuroraStatusColors(' + ', '.join(f'{name}: tokens.{name}.flutterColor' for name in status_names) + ');\n'
mapping += ''.join(f'  final Color {name};\n' for name in status_names)
mapping += '  @override\n  AuroraStatusColors copyWith({' + ', '.join(f'Color? {name}' for name in status_names) + '}) => AuroraStatusColors(' + ', '.join(f'{name}: {name} ?? this.{name}' for name in status_names) + ');\n'
mapping += '  @override\n  AuroraStatusColors lerp(covariant AuroraStatusColors? other, double t) {\n    if (other == null) return this;\n    return AuroraStatusColors(' + ', '.join(f'{name}: Color.lerp({name}, other.{name}, t)!' for name in status_names) + ');\n  }\n}\n'
target = ROOT / 'packages/aurora_flutter/lib/src'
target.mkdir(parents=True, exist_ok=True)
(target / 'material.dart').write_text(mapping, encoding='utf-8')

roles = header + "import 'package:material_color_utilities/material_color_utilities.dart';\nimport 'color.dart';\nimport 'contract.dart';\nimport 'foundation.dart';\n\n"
roles += 'Map<AuroraColorToken, AuroraColor> materialRoleValues(DynamicScheme scheme) => {\n'
for name in MATERIAL:
    source_name = 'inverseOnSurface' if name == 'onInverseSurface' else name
    # Flutter ColorScheme.fromSeed uses resolved primary for surfaceTint.
    if name == 'surfaceTint':
        source_name = 'primary'
    roles += f'  AuroraFoundation.{name}: AuroraColor(scheme.{source_name}),\n'
roles += '};\n'
(ROOT / 'packages/aurora/lib/src/material_roles.dart').write_text(roles, encoding='utf-8')

# Language-independent contract definitions for future adapters and ports.
spec = ROOT / 'spec'
spec.mkdir(exist_ok=True)
(spec / 'foundation-v1.json').write_text(json.dumps({
    'version': 1,
    'namespace': 'colors',
    'tokens': [{'path': f'colors.{name}', 'type': 'color', 'description': desc}
               for name, desc, _, _ in ROWS],
}, indent=2) + '\n', encoding='utf-8')
print(f'Generated {len(ROWS)} foundation roles ({len(MATERIAL)} Material + 12 status).')

# ---------------------------------------------------------------- TypeScript
# The TypeScript core (@aurora/core in packages/aurora_ts) reads the same table.
# Its texture foundation comes from spec/texture-foundation-v1.json, which the
# Dart texture foundation exports (packages/aurora/tool/export_texture_fixture.dart).
ts_src = ROOT / 'packages/aurora_ts/src'
ts_src.mkdir(parents=True, exist_ok=True)
q = json.dumps

ts = header + "import type { AuroraColor } from './color.js';\nimport { AuroraColorToken } from './token.js';\nimport type { AuroraThemeVariant } from './theme.js';\n\n"
for name, desc, _, _ in ROWS:
    ts += f"const {name} = new AuroraColorToken('colors.{name}', {{ description: {q(desc)} }});\n"
ts += '\n/** Aurora foundation v1: current Material color roles plus status roles. */\nexport const AuroraFoundation = Object.freeze({\n  version: 1 as const,\n'
ts += ''.join(f'  {name},\n' for name, *_ in ROWS)
ts += '  tokens: Object.freeze([\n' + ''.join(f'    {name},\n' for name, *_ in ROWS) + '  ]) as readonly AuroraColorToken[],\n});\n\n'
ts += '/** Direct immutable values for the entire app contract. No global active theme. */\nexport class AuroraTokens {\n  constructor(private readonly variant: AuroraThemeVariant) {}\n\n  read(token: AuroraColorToken): AuroraColor {\n    return this.variant.read(token);\n  }\n'
for name, desc, *_ in ROWS:
    ts += f'\n  /** {desc} */\n  get {name}(): AuroraColor {{\n    return this.variant.read({name});\n  }}\n'
ts += '}\n'
(ts_src / 'foundation.ts').write_text(ts, encoding='utf-8')

ts = header + "import { AuroraColor } from './color.js';\nimport type { AuroraColorToken } from './token.js';\nimport { AuroraFoundation as F } from './foundation.js';\n\n"
ts += 'function preset(entries: [AuroraColorToken, string][]): ReadonlyMap<AuroraColorToken, AuroraColor> {\n  return new Map(entries.map(([token, hex]) => [token, AuroraColor.hex(hex)]));\n}\n\n'
ts += '/** Complete explicit foundation presets; app extensions are still required. */\nexport const AuroraStarterValues = Object.freeze({\n'
for appearance, index in [('light', 2), ('dark', 3)]:
    ts += f'  {appearance}: preset([\n' + ''.join(f"    [F.{row[0]}, '#{row[index]}'],\n" for row in ROWS) + '  ]),\n'
ts += '});\n'
(ts_src / 'starters.ts').write_text(ts, encoding='utf-8')

ts = header + "import { AuroraColor } from './color.js';\nimport type { AuroraColorToken } from './token.js';\nimport { AuroraFoundation as F } from './foundation.js';\nimport type { DynamicScheme } from './mcu/dynamic.js';\n\n"
ts += 'export function materialRoleValues(scheme: DynamicScheme): Map<AuroraColorToken, AuroraColor> {\n  return new Map<AuroraColorToken, AuroraColor>([\n'
for name in MATERIAL:
    source_name = 'inverseOnSurface' if name == 'onInverseSurface' else name
    # Flutter ColorScheme.fromSeed uses resolved primary for surfaceTint.
    if name == 'surfaceTint':
        source_name = 'primary'
    ts += f'    [F.{name}, new AuroraColor(scheme.{source_name})],\n'
ts += '  ]);\n}\n'
(ts_src / 'materialRoles.ts').write_text(ts, encoding='utf-8')

# Texture accessor names follow the Dart AuroraTextureFoundation fields; the
# remaining tokens use the last path segment (type.displayLarge -> displayLarge).
TEXTURE_NAMES = {
    'type.family.brand': 'brandFamily', 'type.family.plain': 'plainFamily',
    'shape.extraSmall': 'extraSmallShape', 'shape.small': 'smallShape', 'shape.medium': 'mediumShape',
    'shape.large': 'largeShape', 'shape.extraLarge': 'extraLargeShape',
    'motion.short': 'shortDuration', 'motion.medium': 'mediumDuration', 'motion.long': 'longDuration',
    'motion.extraLong': 'extraLongDuration', 'motion.easing.standard': 'easingStandard',
    'motion.easing.emphasizedDecelerate': 'easingEmphasizedDecelerate',
    'motion.easing.emphasizedAccelerate': 'easingEmphasizedAccelerate',
}
TOKEN_CLASSES = {'fontFamily': 'AuroraFontFamilyToken', 'typography': 'AuroraTypographyToken',
                 'dimension': 'AuroraDimensionToken', 'duration': 'AuroraDurationToken',
                 'cubicBezier': 'AuroraCubicBezierToken'}
texture_spec = json.loads((spec / 'texture-foundation-v1.json').read_text(encoding='utf-8'))
texture_names = {}
for token in texture_spec['tokens']:
    path = token['path']
    texture_names[path] = TEXTURE_NAMES.get(path) or path.rsplit('.', 1)[1]
if len(set(texture_names.values())) != len(texture_names):
    raise SystemExit('Texture accessor names must be unique')


def ts_number(value):
    return repr(float(value)) if isinstance(value, float) else str(value)


def ts_ref(value, kind):
    if isinstance(value, str) and value.startswith('{'):
        return f'new AuroraAlias({texture_names[value[1:-1]]})'
    if kind == 'dimension':
        return f"AuroraDimension.{value['unit']}({ts_number(value['value'])})"
    if kind == 'fontFamily':
        return f'new AuroraFontFamily({q(value if isinstance(value, list) else [value])})'
    if kind == 'fontWeight':
        return f'new AuroraFontWeight({value})'
    if kind == 'number':
        return f'new AuroraLiteral({ts_number(value)})'
    raise SystemExit(f'Unsupported texture starter field type {kind}')


def ts_starter(token):
    kind, value = token['type'], token['starter']
    if kind == 'typography':
        fields = [('fontFamily', 'fontFamily'), ('fontSize', 'dimension'), ('fontWeight', 'fontWeight'),
                  ('letterSpacing', 'dimension'), ('lineHeight', 'number')]
        return 'new AuroraTypography({\n' + ''.join(
            f'      {field}: {ts_ref(value[field], field_kind)},\n' for field, field_kind in fields) + '    })'
    if kind == 'duration':
        if value['unit'] != 'ms':
            raise SystemExit('Texture starter durations must be in ms')
        return f"AuroraDuration.ms({ts_number(value['value'])})"
    if kind == 'cubicBezier':
        return 'new AuroraCubicBezier(' + ', '.join(ts_number(v) for v in value) + ')'
    return ts_ref(value, kind)


ts = header + '// Source: spec/texture-foundation-v1.json, exported from the Dart texture foundation.\n'
ts += "import { AuroraAlias, AuroraLiteral } from './ref.js';\nimport {\n" + ''.join(
    f'  {cls},\n' for cls in sorted(set(TOKEN_CLASSES.values()))) + "  type AuroraToken,\n} from './token.js';\n"
ts += "import {\n  AuroraCubicBezier,\n  AuroraDimension,\n  AuroraDuration,\n  AuroraFontFamily,\n  AuroraFontWeight,\n  AuroraTypography,\n} from './values.js';\n\n"
for token in texture_spec['tokens']:
    ts += f"const {texture_names[token['path']]} = new {TOKEN_CLASSES[token['type']]}({q(token['path'])}, {{\n  description: {q(token['description'])},\n}});\n"
ts += ('\n/**\n * Aurora texture foundation v1: the Material 3 baseline type scale, corner\n'
       ' * shapes and motion. Every texture supplies these; apps add their own tokens as\n'
       ' * texture contract extensions. The `type`, `shape` and `motion` namespaces are\n'
       ' * reserved.\n */\nexport const AuroraTextureFoundation = Object.freeze({\n')
ts += f"  version: {texture_spec['version']} as const,\n  namespaces: Object.freeze({q(texture_spec['namespaces'])}) as readonly string[],\n"
ts += ''.join(f"  {texture_names[t['path']]},\n" for t in texture_spec['tokens'])
ts += '  tokens: Object.freeze([\n' + ''.join(
    f"    {texture_names[t['path']]},\n" for t in texture_spec['tokens']) + '  ]) as readonly AuroraToken<unknown>[],\n});\n\n'
ts += ('/** Material 3 baseline values for every texture foundation token. */\n'
       'export const auroraMaterialTextureValues: ReadonlyMap<AuroraToken<unknown>, unknown> = new Map<\n'
       '  AuroraToken<unknown>,\n  unknown\n>([\n')
for token in texture_spec['tokens']:
    ts += f"  [\n    {texture_names[token['path']]},\n    {ts_starter(token)},\n  ],\n"
ts += ']);\n'
(ts_src / 'textureFoundation.ts').write_text(ts, encoding='utf-8')
print(f'Generated TypeScript foundation ({len(ROWS)} colour roles, {len(texture_spec["tokens"])} texture tokens).')
