"""Regenerate checked-in foundation accessors and Flutter mapping from one table.

This is repository maintenance tooling, not Aurora's future theme generator.
Run from any directory: python tools/generate_foundation.py
"""
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
ROWS = []

def add(name, description, light, dark):
    ROWS.append((name, description, light, dark))

for name, label, light, dark in [
    ('primary', 'prominent actions', ['6750a4', 'ffffff', 'eaddff', '21005d'], ['d0bcff', '381e72', '4f378b', 'eaddff']),
    ('secondary', 'less prominent actions', ['625b71', 'ffffff', 'e8def8', '1d192b'], ['ccc2dc', '332d41', '4a4458', 'e8def8']),
    ('tertiary', 'contrasting accents', ['7d5260', 'ffffff', 'ffd8e4', '31111d'], ['efb8c8', '492532', '633b48', 'ffd8e4']),
]:
    cap = name.capitalize()
    add(name, f'Accent for {label}.', light[0], dark[0])
    add('on' + cap, f'Text and icons on {name}.', light[1], dark[1])
    add(name + 'Container', f'Lower-emphasis container for {label}.', light[2], dark[2])
    add('on' + cap + 'Container', f'Text and icons on {name}Container.', light[3], dark[3])
    add(name + 'Fixed', f'Container accent that stays constant across appearances.', light[2], light[2])
    add(name + 'FixedDim', f'Stronger fixed {name} accent.', dark[0], dark[0])
    add('on' + cap + 'Fixed', f'Text and icons on fixed {name} accents.', light[3], light[3])
    add('on' + cap + 'FixedVariant', f'Lower-emphasis content on fixed {name} accents.', dark[2], dark[2])

for name, description, light, dark in [
    ('error', 'Error and destructive feedback.', 'b3261e', 'f2b8b5'),
    ('onError', 'Text and icons on error.', 'ffffff', '601410'),
    ('errorContainer', 'Lower-emphasis error container.', 'f9dedc', '8c1d18'),
    ('onErrorContainer', 'Text and icons on errorContainer.', '410e0b', 'f9dedc'),
    ('surface', 'Default page and component surface.', 'fffbfe', '141218'),
    ('onSurface', 'Primary text and icons on surfaces.', '1c1b1f', 'e6e0e9'),
    ('surfaceDim', 'Dimmest surface tone.', 'ded8e1', '141218'),
    ('surfaceBright', 'Brightest surface tone.', 'fffbfe', '3b383e'),
    ('surfaceContainerLowest', 'Lowest surface container level.', 'ffffff', '0f0d13'),
    ('surfaceContainerLow', 'Low surface container level.', 'f7f2fa', '1d1b20'),
    ('surfaceContainer', 'Default distinct surface container.', 'f3edf7', '211f26'),
    ('surfaceContainerHigh', 'High surface container level.', 'ece6f0', '2b2930'),
    ('surfaceContainerHighest', 'Highest surface container level.', 'e6e0e9', '36343b'),
    ('onSurfaceVariant', 'Lower-emphasis text and icons on surfaces.', '49454f', 'cac4d0'),
    ('outline', 'Boundaries requiring emphasis.', '79747e', '938f99'),
    ('outlineVariant', 'Subtle decorative boundaries and dividers.', 'cac4d0', '49454f'),
    ('shadow', 'Color of cast shadows.', '000000', '000000'),
    ('scrim', 'Color of obscuring modal overlays.', '000000', '000000'),
    ('inverseSurface', 'Surface contrasting with surrounding appearance.', '313033', 'e6e0e9'),
    ('onInverseSurface', 'Text and icons on inverseSurface.', 'f4eff4', '313033'),
    ('inversePrimary', 'Primary accent on inverseSurface.', 'd0bcff', '6750a4'),
    ('surfaceTint', 'Accent used by Material surface tint treatments.', '6750a4', 'd0bcff'),
]:
    add(name, description, light, dark)

MATERIAL = [r[0] for r in ROWS]
for name, light, dark in [
    ('success', ['146c2e', 'ffffff', 'a6f5b0', '002108'], ['8bd996', '003915', '005321', 'a6f5b0']),
    ('warning', ['805600', 'ffffff', 'ffdea6', '281900'], ['f4bf60', '442c00', '614000', 'ffdea6']),
    ('info', ['0061a4', 'ffffff', 'd1e4ff', '001d36'], ['9ecaff', '003258', '00497d', 'd1e4ff']),
]:
    cap = name.capitalize()
    for token, description, index in [
        (name, f'{cap} feedback.', 0),
        ('on' + cap, f'Text and icons on {name}.', 1),
        (name + 'Container', f'Lower-emphasis {name} container.', 2),
        ('on' + cap + 'Container', f'Text and icons on {name}Container.', 3),
    ]:
        add(token, description, light[index], dark[index])

header = '// Generated by tools/generate_foundation.py. Edit that table, then regenerate.\n'
foundation = header + "import 'color.dart';\nimport 'contract.dart';\nimport 'theme.dart';\n\n"
foundation += '/// Aurora foundation v1: current Material color roles plus status roles.\nabstract final class AuroraFoundation {\n  static const version = 1;\n'
for name, desc, _, _ in ROWS:
    foundation += f"  static const {name} = AuroraColorToken('colors.{name}', description: '{desc}');\n"
foundation += '  static const tokens = <AuroraColorToken>[\n' + ''.join(f'    {r[0]},\n' for r in ROWS) + '  ];\n}\n\n'
foundation += '/// Direct immutable values for the entire app contract. No global active theme.\nfinal class AuroraTokens {\n  const AuroraTokens(this._variant);\n  final AuroraThemeVariant _variant;\n  AuroraColor read(AuroraColorToken token) => _variant.read(token);\n'
for name, *_ in ROWS:
    foundation += f'  AuroraColor get {name} => _variant.read(AuroraFoundation.{name});\n'
foundation += '}\n'
(ROOT / 'packages/aurora/lib/src/foundation.dart').write_text(foundation, encoding='utf-8')

starters = header + "import 'color.dart';\nimport 'contract.dart';\nimport 'foundation.dart';\nimport 'theme.dart';\n\n"
starters += '/// Complete explicit foundation presets; app extensions are still required.\nabstract final class AuroraStarter {\n'
for appearance, index in [('light', 2), ('dark', 3)]:
    starters += f'  static final Map<AuroraColorToken, AuroraColor> {appearance} = Map.unmodifiable({{\n'
    for row in ROWS:
        starters += f"    AuroraFoundation.{row[0]}: AuroraColor.hex('#{row[index]}'),\n"
    starters += '  });\n'
starters += '''  static AuroraThemeVariant variant({
    required AuroraContract contract,
    required AuroraAppearance appearance,
    Map<AuroraColorToken, AuroraColor> values = const {},
  }) => AuroraThemeVariant(
    contract: contract,
    appearance: appearance,
    values: {...(appearance == AuroraAppearance.light ? light : dark), ...values},
  );
}
'''
(ROOT / 'packages/aurora/lib/src/starters.dart').write_text(starters, encoding='utf-8')

mapping = header + "import 'package:aurora/aurora.dart';\nimport 'package:flutter/material.dart';\n\n"
mapping += '''extension AuroraFlutterColor on AuroraColor {
  Color get flutterColor => Color(argb);
}

/// Supplies every nondeprecated Material color role explicitly.
extension AuroraMaterialVariant on AuroraThemeVariant {
  ColorScheme toColorScheme() => ColorScheme(
    brightness: appearance == AuroraAppearance.light ? Brightness.light : Brightness.dark,
'''
mapping += ''.join(f'    {name}: colors.{name}.flutterColor,\n' for name in MATERIAL)
mapping += '  );\n  ThemeData toThemeData() => ThemeData(useMaterial3: true, colorScheme: toColorScheme());\n}\n'
target = ROOT / 'packages/aurora_flutter/lib/src'
target.mkdir(parents=True, exist_ok=True)
(target / 'material.dart').write_text(mapping, encoding='utf-8')

roles = header + "import 'package:material_color_utilities/material_color_utilities.dart';\nimport 'color.dart';\nimport 'contract.dart';\nimport 'foundation.dart';\n\n"
roles += 'Map<AuroraColorToken, AuroraColor> materialRoleValues(DynamicScheme scheme) => {\n'
for name in MATERIAL:
    source_name = 'inverseOnSurface' if name == 'onInverseSurface' else name
    roles += f'  AuroraFoundation.{name}: AuroraColor(scheme.{source_name}),\n'
roles += '};\n'
(ROOT / 'packages/aurora/lib/src/material_roles.dart').write_text(roles, encoding='utf-8')

# Language-independent contract definitions for future adapters and ports.
spec = ROOT / 'spec'
spec.mkdir(exist_ok=True)
(spec / 'foundation-v1.json').write_text(json.dumps({
    'version': 1,
    'namespace': 'colors',
    'tokens': [{'path': f'colors.{name}', 'type': 'color', 'description': desc}
               for name, desc, _, _ in ROWS],
}, indent=2) + '\n', encoding='utf-8')
print(f'Generated {len(ROWS)} foundation roles ({len(MATERIAL)} Material + 12 status).')
