// @aurora/react-native: the React Native adapter for Aurora.
export { AuroraController, type AuroraControllerInit, systemAppearance } from './controller.js';
export {
  AuroraNativeUnsupportedError,
  type AuroraNativeBorderStyle,
  type AuroraNativeBoxShadow,
  type AuroraNativeCubicBezier,
  type AuroraNativeFontFamilyResolver,
  type AuroraNativeFontWeight,
  type AuroraNativeLengthOptions,
  type AuroraNativeMode,
  type AuroraNativeOptions,
  type AuroraNativeOutput,
  type AuroraNativeResult,
  type AuroraNativeShadowStyle,
  type AuroraNativeStrokeStyle,
  type AuroraNativeTextureReader,
  type AuroraNativeTypographyOptions,
  type AuroraNativeTypographyStyle,
  type AuroraNativeUnsupported,
  nativeBorder,
  nativeBorderRadius,
  nativeColor,
  nativeColorWithAlpha,
  nativeCubicBezier,
  nativeDimension,
  nativeDuration,
  nativeShadow,
  nativeStrokeStyle,
  nativeTypography,
} from './native.js';
export {
  AuroraFixedScope,
  type AuroraFixedScopeProps,
  AuroraProvider,
  type AuroraProviderProps,
  type AuroraScopeHandle,
  type AuroraScopeSnapshot,
  type AuroraTextureView,
  useAuroraController,
  useAuroraScope,
  useAuroraState,
  useAuroraTexture,
  useAuroraToken,
  useAuroraTokens,
  useAuroraVariant,
  useMaybeAuroraTexture,
} from './scope.js';
